# Generated by Django 5.2.3 on 2025-07-22 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deartment",
            fields=[
                ("deptid", models.AutoField(primary_key=True, serialize=False)),
                ("deptname", models.TextField(max_length=25)),
                ("deptloc", models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("empid", models.AutoField(primary_key=True, serialize=False)),
                ("empname", models.TextField(max_length=30)),
                ("empage", models.IntegerField()),
                ("empsalary", models.IntegerField()),
                (
                    "empdepartment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dbapp.deartment",
                    ),
                ),
            ],
        ),
    ]
