# Generated by Django 5.2.3 on 2025-07-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deartment",
            name="deptloc",
            field=models.TextField(max_length=30),
        ),
    ]
