# Generated by Django 5.2.3 on 2025-07-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbapp", "0002_alter_deartment_deptloc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deartment",
            name="deptloc",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="deartment",
            name="deptname",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="employee",
            name="empname",
            field=models.CharField(max_length=30),
        ),
    ]
